"use client"

import { motion } from "framer-motion"
import { ArrowUpRight } from "lucide-react"

const projects = [
  { number: "01", title: "DYDO", type: "Commerce / Product design", description: "A sharper digital storefront for a beverage brand ready to move faster.", stack: "React · Redux Toolkit · Node.js", result: "Conversion-led shopping flow" },
  { number: "02", title: "Caseflow", type: "Operations / Internal tooling", description: "A complaint management system that turns scattered requests into accountable workflows.", stack: "React · REST APIs · Node.js", result: "Clear ownership at every stage" },
  { number: "03", title: "Archive", type: "Enterprise / Document systems", description: "A calm, searchable home for the documents teams depend on every day.", stack: "Next.js · React · Node.js", result: "Less time lost to manual search" },
  { number: "04", title: "Service Desk", type: "Customer experience / Portal", description: "A mobile-first request experience that keeps customers informed from start to finish.", stack: "React · Angular · JavaScript", result: "Smoother service delivery" },
]

export default function Projects() {
  return <section id="projects" className="border-b border-border px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1400px]"><div className="mb-14 grid gap-6 lg:grid-cols-[1fr_320px]"><div><p className="mb-5 font-mono text-xs uppercase tracking-[0.24em] text-primary">Selected work / 2022—2026</p><h2 className="display max-w-3xl text-5xl font-medium sm:text-7xl">A small selection of <span className="text-muted-foreground">useful things.</span></h2></div><p className="self-end text-sm leading-6 text-muted-foreground">I work across product direction, interface design, and the engineering needed to make the experience feel inevitable.</p></div><div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2">{projects.map((project, index) => <motion.article key={project.number} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.05 }} className="group bg-background p-6 transition-colors hover:bg-card sm:p-10"><div className="flex items-start justify-between"><span className="font-mono text-xs text-muted-foreground">{project.number}</span><ArrowUpRight className="text-muted-foreground transition-transform group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-primary" aria-hidden="true" /></div><div className="mt-20"><p className="font-mono text-xs uppercase tracking-[0.16em] text-primary">{project.type}</p><h3 className="mt-4 text-4xl font-medium tracking-[-0.06em] sm:text-5xl">{project.title}</h3><p className="mt-5 max-w-md leading-7 text-muted-foreground">{project.description}</p></div><div className="mt-12 flex flex-col gap-4 border-t border-border pt-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span className="font-mono">{project.stack}</span><span className="text-foreground">{project.result}</span></div></motion.article>)}</div></div></section>
}
