"use client"

import { motion } from "framer-motion"
import { ArrowUpRight, CheckCircle2 } from "lucide-react"

const projects = [
  { number: "01", title: "DYDO Beverage Commerce", type: "E-commerce platform", description: "A conversion-focused shopping experience that makes product discovery, cart flows, and checkout feel effortless.", stack: "React · Redux Toolkit · Tailwind · Node.js", result: "Faster path from discovery to checkout", tone: "from-primary/20" },
  { number: "02", title: "Complaint Management System", type: "Operations product", description: "A focused internal workflow that gives teams ownership, visibility, and measurable resolution progress.", stack: "React · Redux · REST APIs · Node.js", result: "Clearer ownership across every case", tone: "from-accent/20" },
  { number: "03", title: "E-Document Archive", type: "Enterprise system", description: "A structured document workspace with search, categorization, and secure file management for growing teams.", stack: "Next.js · React · Node.js · State management", result: "Less time lost searching for information", tone: "from-primary/20" },
  { number: "04", title: "Technical Service Portal", type: "Service experience", description: "A mobile-first request platform that keeps customers informed from submission through completion.", stack: "React · Angular · JavaScript · CSS", result: "A smoother service experience end to end", tone: "from-accent/20" },
]

export default function Projects() {
  return <section id="projects" className="border-t border-border px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-12 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-3 font-mono text-xs uppercase tracking-[0.22em] text-primary">Selected work</p><h2 className="max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">Digital products built to create <span className="text-gradient">momentum.</span></h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">A few products, systems, and experiences where strategy meets careful execution.</p></div><div className="grid gap-5 md:grid-cols-2">{projects.map((project, index) => <motion.article key={project.number} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.06 }} className="group relative overflow-hidden rounded-3xl border border-border bg-card p-6 transition-transform hover:-translate-y-1 sm:p-8"><div className={`pointer-events-none absolute inset-x-0 top-0 h-32 bg-gradient-to-b ${project.tone} to-transparent opacity-60`} aria-hidden="true" /><div className="relative flex items-start justify-between"><span className="font-mono text-xs text-primary">{project.number} / {project.type}</span><ArrowUpRight className="text-muted-foreground transition-transform group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-primary" aria-hidden="true" /></div><div className="relative mt-20"><h3 className="text-2xl font-semibold tracking-tight sm:text-3xl">{project.title}</h3><p className="mt-4 max-w-lg leading-7 text-muted-foreground">{project.description}</p><p className="mt-6 inline-flex items-center gap-2 rounded-full bg-secondary px-3 py-1.5 text-xs font-medium text-secondary-foreground"><CheckCircle2 className="size-3.5 text-primary" aria-hidden="true" /> {project.result}</p></div><p className="relative mt-8 border-t border-border pt-5 font-mono text-xs text-primary">{project.stack}</p></motion.article>)}</div></div></section>
}
