"use client"

import { motion } from "framer-motion"
import { ArrowUpRight } from "lucide-react"
import { Reveal } from "@/components/motion-layer"

const projects = [{ number: "01", title: "DYDO", type: "Commerce / Product direction", description: "A sharper digital storefront for a beverage brand ready to move faster.", stack: "React · Redux Toolkit · Node.js", result: "Conversion-led shopping flow" }, { number: "02", title: "Caseflow", type: "Operations / Internal systems", description: "A complaint management system that turns scattered requests into accountable workflows.", stack: "React · REST APIs · Node.js", result: "Clear ownership at every stage" }, { number: "03", title: "Archive", type: "Enterprise / Document systems", description: "A calm, searchable home for the documents teams depend on every day.", stack: "Next.js · React · Node.js", result: "Less time lost to manual search" }, { number: "04", title: "Service Desk", type: "Customer experience / Portal", description: "A mobile-first request experience that keeps customers informed from start to finish.", stack: "React · Angular · JavaScript", result: "Smoother service delivery" }]

export default function Projects() { return <section id="projects" className="border-b border-border px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1400px]"><Reveal><div className="mb-20 flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow mb-5 text-primary">01 / Selected work</p><h2 className="display max-w-3xl text-6xl sm:text-8xl">Work that <em className="text-primary">moves.</em></h2></div><p className="max-w-sm text-base leading-7 text-muted-foreground">A selection of products and platforms shaped from first thought to final detail.</p></div></Reveal><div className="grid gap-0 border-t border-border">{projects.map((project, index) => <motion.article key={project.number} initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} whileHover={{ x: 8 }} viewport={{ once: true, margin: "-50px" }} transition={{ delay: index * .08, duration: .65 }} className="group grid gap-6 border-b border-border py-9 lg:grid-cols-[80px_1fr_1fr_48px] lg:items-center lg:gap-10"><span className="eyebrow text-primary">{project.number}</span><div><p className="eyebrow text-muted-foreground">{project.type}</p><h3 className="mt-3 font-serif text-5xl tracking-[-.06em] transition-colors duration-300 group-hover:text-primary sm:text-6xl">{project.title}</h3></div><div className="grid gap-4 sm:grid-cols-2"><p className="leading-7 text-muted-foreground">{project.description}</p><div className="text-sm"><p className="text-foreground">{project.result}</p><p className="mt-2 font-mono text-xs text-muted-foreground">{project.stack}</p></div></div><ArrowUpRight className="text-primary transition-transform duration-300 group-hover:-translate-y-1 group-hover:translate-x-1" aria-hidden="true" /></motion.article>)}</div></div></section> }
