"use client"

import { motion } from "framer-motion"
import { Code2, Database, Layout, Zap } from "lucide-react"
import { Reveal, Stagger, StaggerItem, Tilt } from "@/components/motion-layer"

const groups = [{ title: "Interface", icon: Layout, description: "Interfaces that feel simple because the hard decisions happened upstream.", items: "React · Next.js · Angular · TypeScript" }, { title: "Systems", icon: Database, description: "Reliable backends and APIs that keep the product moving when usage grows.", items: "Node.js · .NET · REST APIs · SQL" }, { title: "Engineering", icon: Code2, description: "Clean, maintainable code with the right architecture for the stage you are in.", items: "Redux · Git · Testing · Code reviews" }, { title: "Momentum", icon: Zap, description: "Fast collaboration, clear communication, and ownership from kickoff to launch.", items: "Discovery · Prototyping · Leadership · Delivery" }]

export default function Skills() { return <section id="skills" className="border-b border-border px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1400px]"><Reveal><div className="mb-14 grid gap-6 lg:grid-cols-[1fr_320px]"><div><p className="mb-5 font-mono text-xs uppercase tracking-[0.24em] text-primary">Capabilities</p><h2 className="display max-w-3xl text-5xl font-medium sm:text-7xl">The useful parts of <span className="text-muted-foreground">the stack.</span></h2></div><p className="self-end text-sm leading-6 text-muted-foreground">A product-minded approach to the pieces that make a digital experience credible: clarity, craft, and dependable execution.</p></div></Reveal><Stagger className="grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{groups.map((group, index) => { const Icon = group.icon; return <StaggerItem key={group.title}><Tilt className="h-full"><motion.article whileHover={{ y: -10 }} className="h-full bg-background p-6 sm:p-8"><motion.div whileHover={{ rotate: 12, scale: 1.15 }} transition={{ type: "spring", stiffness: 300 }}><Icon className="mb-16 size-7 text-primary" aria-hidden="true" /></motion.div><p className="font-mono text-xs text-muted-foreground">0{index + 1}</p><h3 className="mt-3 text-2xl font-medium">{group.title}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{group.description}</p><p className="mt-8 border-t border-border pt-4 font-mono text-xs leading-5 text-primary">{group.items}</p></motion.article></Tilt></StaggerItem> })}</Stagger></div></section> }
