"use client"

import { motion } from "framer-motion"
import { Quote } from "lucide-react"
import { Reveal, Stagger, StaggerItem, Tilt } from "@/components/motion-layer"

const reviews = [{ name: "Munir Shabeer", company: "munirshabeer.com", quote: "Adeel was excellent from start to finish. He understood the goal quickly, communicated clearly, and delivered a polished experience that feels fast, professional, and easy to use." }, { name: "Product partner", company: "Enterprise web platform", quote: "A thoughtful developer who balances product details with dependable engineering. The result was a cleaner interface and a much smoother workflow for our users." }, { name: "Startup founder", company: "Digital product launch", quote: "Adeel brought structure to a complex build, kept every milestone moving, and turned our ideas into a responsive product we were proud to share." }]

export default function Testimonials() { return <section id="reviews" className="border-b border-border px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1400px]"><Reveal><div className="mb-20 max-w-3xl"><p className="eyebrow mb-5 text-primary">05 / Client notes</p><h2 className="display text-6xl sm:text-8xl">The best work is <em className="text-primary">shared.</em></h2></div></Reveal><Stagger className="grid gap-12 lg:grid-cols-3">{reviews.map((review) => <StaggerItem key={review.name}><Tilt><motion.article whileHover={{ y: -10 }} className="flex min-h-[280px] flex-col justify-between border-t border-border pt-6"><motion.div whileHover={{ rotate: 12 }}><Quote className="size-6 text-primary" aria-hidden="true" /></motion.div><p className="mt-8 text-xl leading-8 tracking-tight">&quot;{review.quote}&quot;</p><div className="mt-10"><p className="font-medium">{review.name}</p><p className="mt-1 text-sm text-muted-foreground">{review.company}</p></div></motion.article></Tilt></StaggerItem>)}</Stagger></div></section> }
